# THIS FILE WILL BE AUTOGENERATED BY THE GRADLE SCRIPT. EDITING WILL BE DISALLOWED THEN.

require 'jar_dependencies'
require_jar('org.logstash.javaapi', 'logstash-output-java_output_example', '0.0.1')
