# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.
# encoding: utf-8
require "logstash/outputs/base"
require "logstash/namespace"
require "logstash-output-java_output_example_jars"
require "java"

class LogStash::Outputs::JavaOutputExample < LogStash::Outputs::Base
  config_name "java_output_example"

  def self.javaClass() org.logstash.javaapi.JavaOutputExample.java_class; end
end
